[tool.black]
line-length = 100

[tool.pycln]
all = true

[tool.isort]
profile="black"
line_length = 100
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
known_first_party = ['Laboratory']
sections = ['FUTURE', 'STDLIB', 'THIRDPARTY', 'FIRSTPARTY', 'LOCALFOLDER']
default_section = "THIRDPARTY"